# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
