# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-19 00:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0002_playlist_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientsuserneeds',
            name='drinks',
        ),
        migrations.RemoveField(
            model_name='ingredientsuserneeds',
            name='user',
        ),
        migrations.DeleteModel(
            name='IngredientsUserNeeds',
        ),
    ]
