# Generated by Django 2.0.12 on 2019-03-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0003_auto_20180319_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
